### PR TITLE
Every dark color can be changed in styleDark.scss

### LINKED ISSUE #28: Add Dark Mode

### PR DESCRIPTION
**Pull request by Agnitor44**
I came up with this dark theme mode. I was happy to work with that even if it will be not use.
Have a nice day.

### CODE REVIEW

**Comment by stephin007** [comment]
Hey @Agnitor44 thanx for your input will check and revert here asap! :)

**Review by maxpainnogain1 — COMMENTED** [review]
Great job

**Comment by stephin007** [comment]
@Agnitor44 i checked your changes, you have done a wonderful work, but few points to consider.
- the alignment of the button is not proper, i mean that sun and moon icon its aligned too much to the left , i prefer that you keep it in the right side of the navbar with proper justification(i.e. not too much aligned to the right/left).
- The colors chosen are not that much good, can you change to a better color gradients for dark mode.

please do the changes in this PR only. 😃

**Comment by stephin007** [comment]
checking it @Agnitor44 , will let you know!

**Comment by stephin007** [comment]
hey @Agnitor44 
- on reloading the dark mode does not stay, it gets switched back to light mode(this was mentioned above as well, please try to fix this)
- Also, now the gradients look much better, but the other font colors still look dull... can you find a suitable colors to all the text colors which go with  the gradient color of the dark mode.

**Review by stephin007 — APPROVED** [review]
LOOKS GOOD TO ME! 🔥

**Comment by stephin007** [comment]
Great Work @Agnitor44 !
mail us and join us to work on more stuff

**Pull request merged**
